"""empty message

Revision ID: cf9394f6f11a
Revises: 7832eaf03e8f
Create Date: 2017-12-16 12:30:37.190487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9394f6f11a'
down_revision = '7832eaf03e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('member', 'location')
    with op.batch_alter_table('member') as batch_op:
        batch_op.drop_column('location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
