"""empty message

Revision ID: 77057a55ca23
Revises: c71f57e8290d
Create Date: 2017-07-12 14:58:04.531344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77057a55ca23'
down_revision = 'c71f57e8290d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscribed')
    # ### end Alembic commands ###
