"""empty message

Revision ID: 3c5fb0f2491f
Revises: 77057a55ca23
Create Date: 2017-07-12 15:12:53.148988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c5fb0f2491f'
down_revision = '77057a55ca23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('order', 'orders')
    # ### end Alembic commands ###
